version: "3.8"
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    env_file:
    - .env 
    ports:
    - "1849:3306"
    volumes:
    - "cpr:/data"
    networks:
    - net3

volumes:
  cpr:
networks:
  net3:
